### ISSUE TITLE
API der Bundesnetzagentur macht Probleme

### ISSUE THREAD

**Issue by Hackyy** [KoelnAPI/data#12]
Ich bin per Zufall auf dieses Projekt gestoßen und habe entdeckt, das du die API der Funkmasten der Bundesnetzagentur auslesen tust. 

Siehe:
https://github.com/KoelnAPI/data/blob/master/data/communication/bundesnetzagentur-emf/download.py

@marians Funktioniert das Skript bei dir noch ? Ich habe das bereits ausprobiert. Das Skript ladet leider keine Daten vom Server. Ich habe das Skript auf PHP portiert, dort läuft es leider auch nicht.
 
Könntest du dazu Rückmeldung geben ?
Danke :)

**Comment by marians** [comment]
Ich habe gerade mal in die aktuelle Webanwendung unter http://emf3.bundesnetzagentur.de/karte/default.aspx geguckt. Offenbar werden da Daten vom Server in irgend einer Form verschlüsselt ausgegeben. Ich habe mir jetzt nicht die Mühe gemacht, den Mechanismus näher anzusehen - sollte ja in irgend einer Form im Code nachvollziehbar sein.

Das Script kann so wohl leider nicht mehr funktionieren. Tut mir leid.

**Comment by Hackyy** [comment]
Danke für die schnelle Antwort.
Das ist natürlich auch ein Problem.

**Comment by marians** [comment]
Wie erwartet steht alles nötige zur Entschlüsselung lesbar im JavaScript-Code.

**Comment by Hackyy** [comment]
Das hab ich auch grade entdeckt :) ich habe nur das Problem, dass die API keine Daten ausgibt sobald ich einen Request sende. Ich mach das eigentlich wie du. Erst eine Session über den GET-Request von der Startseite beziehen und dann den POST-Request auf die entsprechende API URL.  Leider werd ich nur auf eine Fehlerseite der Bundesnetzagentur weitergeleitet. 
Deswegen wäre es interessant gewesen ob das Skript bei dir noch läuft. 
Mit Python hab ich leider nicht viel Erfahrung - da muss ich mich erst einarbeiten und schauen ob wenigstens dort die Daten (verschlüsselt) zurückkommen. 
Danke für die Infos :)
