### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [KoelnAPI/data#8]
Die Daten sollten auch im JSON-LD Format angeboten werden. Damit können dann auch die Linked Data Communities auf einfache Weise etwas mit den Daten anfangen.

Ich prüfe wie vorgegangen werden kann.

**Comment by pudo** [comment]
Kleiner Indianerjunge sagt: 

> Erst wenn das letzte Triple generiert, die letzte Ontologie standarisiert, die letzte URI dereferenziert ist, werdet Ihr merken, dass man RDF nicht essen kann.

**Comment by akuckartz** [comment]
@pudo Das gilt generell für offene Daten - und sogar ganz allgemein für Daten. Dennoch danke für den Kommentar ;-)

**Comment by marians** [comment]
@pudo +1

Wer die hier freiwillig angebotenen Daten in JSON-LD übersetzen will, kann das gerne tun. Ich stelle dafür mangels Interesse keine Zeit zur Verfügung.

**Comment by akuckartz** [comment]
@marians Niemand erwartet von dir, dass du dafür Interesse oder Zeit aufbringst - ich schon gar nicht. Und ich hatte eingangs geschrieben:
> Ich prüfe wie vorgegangen werden kann.

Laut dem vorgestern veröffentlichten Zeit-Artikel hast du dich aus KölnAPI "weitestgehend" zurückgezogen:

> So zieht sich auch Marian Steinbach nun weitestgehend aus KölnAPI zurück, das jetzt von Marcus Belledin organisiert wird.
http://www.zeit.de/2015/04/open-data-daten-behoerden-oeffentlichkeit-digital-zugaenglich/seite-2

Insofern finde ich weniger deinen Kommentar als das _Schliessen_ dieses Issue befremdlich. Hast du etwas dagegen, dass andere das aufgreifen? Falls ja: Warum?

**Comment by pudo** [comment]
Eigentlich gar nicht meine Spielwiese hier, aber dennoch: ich glaube man kann schon ein Argument machen. Nämlich, dass eine sekundäre Repräsentation aller Ressourcen in diesem Repo die Komplexität des Workflows und der Verwaltung hoch treibt.

Gleichzeitig sind mir kaum Open Data-Anwendungen auf der Basis von RDF bekannt, die das Stadium einer universitären Machbarkeitsstudie jemals überschritten haben. (Freue mich da über tolle Gegenbeispiele, Bedingung: User-facing, nicht Datenintegrations-Masturbation). 

Kosten/Nutzen ist also grottig.

**Comment by akuckartz** [comment]
@pudo Zu Absatz 2 kann ich mich gerne genauer äussern. Hier scheint mir aber gegenwärtig nicht der richtige Platz dafür zu sein, da das für Marian anscheinend ein rotes Tuch ist. Deshalb muss der Hinweis auf die Verwendung von JSON-LD durch Google hier ausreichen.

Nach meinem Verständnis handelt es sich bei den Resourcen hier im Repository bereits um eine "sekundäre Repräsentation" bereits an anderer Stelle veröffentlichter Daten.

Was die "Komplexität des Workflows und der Verwaltung" angeht: Deren aktuellen Stand habe ich bisher nicht genauer angesehen. Ich verweise deshalb noch einmal auf den Eingangssatz: "Ich prüfe wie vorgegangen werden kann."

**Comment by akuckartz** [comment]
@pudo Ich habe mir exemparisch einige der Skipte hier im Repository angesehen. Weshalb eine Ergänzung der Erzeugung von JSON-LD-Dateien zu einer Erhöhung der "Komplexität des Workflows und der Verwaltung" führen soll ist für mich nicht nachvollziehbar. EIn Anzeichen von Semaphobie?

Das eigentliche Problem ist aus meiner Sicht, dass die Originaldaten nicht bereits in allen zeitgemäßen Formaten angeboten werden. Das betrifft insbesondere die Daten der Stadt Köln, die dies ändern kann und die Absicht zum Angebot von Linked Data auch bereits gegenüber dem Stadtrat erklärt hat - ohne jedoch Termine dafür zu nennen oder sonst konkret zu werden.

**Comment by marians** [comment]
@akuckartz 

Wenn Du gerne Daten aus diesem Repository hier in JSON-LD übersetzen möchtest, halte ich Dich nicht davon ab. Tu es bitte an einem Ort, wo Du volle Kontrolle darüber hast, was Du tust. Mach es so, dass es nicht von irgend einer Interaktion mit mir abhängt.

Mit Deinen Kommentaren erweckst Du bei mir den Eindruck, als sei dieses Repository hier Deiner Meinung nach eine offizielle Institution und der Betreiber verpflichtet, jeden Beitrag dadurch zu würdigen, dass man sich mit ihm intensiv auseinandersetzt.

Ich sage Dir, wie ich es sehe: Dieses Repository habe ich aufgesetzt, weil ich mal Lust dazu hatte. Ich habe eine Weil meine Zeit hinein gesteckt. Das war eine Art Hobby. Inzwischen habe ich nur noch sehr begrenzte Zeit für dieses Hobby, weshalb ich mir sehr genau aussuchen möchte, womit ich diese Zeit verbringe.

Du kannst gerne weiter Feature vorschlagen, Bugs melden, Pull Requests senden. Aber behalte im Hinterkopf, dass ich mich nicht verpflichtet fühle, darauf in irgend einer Form zu reagieren.

**Comment by akuckartz** [comment]
@marians Danke für die klare Aussage. Dein Eindruck täuscht aber. http://www.koelnapi.de/ verweist auf dieses Repository und _dort_ wird der Eindruck erweckt, dass es sich _gerade nicht_ (nur) um ein persönliches Projekt (und ein entsprechendes Repository) handelt.
